import Foundation

extension VoiceRules {
    static let italian = VoiceRules(
        locale: Locale(identifier: "it-IT"),
        speechRecognizerLocale: Locale(identifier: "it-IT"),
        shotKeywords: [
            .init(keyword: "due", eventPrefix: "stat.two"),
            .init(keyword: "due punti", eventPrefix: "stat.two"),
            .init(keyword: "du", eventPrefix: "stat.two"),
            .init(keyword: "2", eventPrefix: "stat.two"),
            .init(keyword: "tre", eventPrefix: "stat.three"),
            .init(keyword: "tre punti", eventPrefix: "stat.three"),
            .init(keyword: "trè", eventPrefix: "stat.three"),
            .init(keyword: "3", eventPrefix: "stat.three"),
            .init(keyword: "tripla", eventPrefix: "stat.three"),
            .init(keyword: "tripla punti", eventPrefix: "stat.three"),
            .init(keyword: "layup", eventPrefix: "stat.layup"),
            .init(keyword: "lay up", eventPrefix: "stat.layup"),
            .init(keyword: "media", eventPrefix: "stat.midRange"),
            .init(keyword: "media distanza", eventPrefix: "stat.midRange"),
            .init(keyword: "mezza distanza", eventPrefix: "stat.midRange"),
            .init(keyword: "dentro", eventPrefix: "stat.paint"),
            .init(keyword: "pitturato", eventPrefix: "stat.paint"),
            .init(keyword: "piturato", eventPrefix: "stat.paint"),
            .init(keyword: "tiro libero", eventPrefix: "stat.freeThrow"),
            .init(keyword: "tiro libro", eventPrefix: "stat.freeThrow"),
            .init(keyword: "libero", eventPrefix: "stat.freeThrow"),
            .init(keyword: "libbero", eventPrefix: "stat.freeThrow"),
            .init(keyword: "libro", eventPrefix: "stat.freeThrow"),
            .init(keyword: "bonus", eventPrefix: "stat.bonus"),
            .init(keyword: "e uno", eventPrefix: "stat.bonus"),
            .init(keyword: "e un", eventPrefix: "stat.bonus"),
        ],
        madeStates: ["segnato", "fatto", "dentro", "buono", "riuscito"],
        missedStates: ["sbagliato", "fuori", "bloccato", "mancato", "no", "aria"],
        statEvents: [
            ("fallo", "stat.foul"),
            ("falo", "stat.foul"),
            ("falo", "stat.foul"),
            ("rimbalzo", "stat.rebound"),
            ("rimbalso", "stat.rebound"),
            ("rimbalzo offensivo", "stat.offensiveRebound"),
            ("rimbalzo difensivo", "stat.defensiveRebound"),
            ("rimbalso offensivo", "stat.offensiveRebound"),
            ("rimbalso difensivo", "stat.defensiveRebound"),
            ("assist", "stat.assist"),
            ("asist", "stat.assist"),
            ("stoppata", "stat.block"),
            ("stòppata", "stat.block"),
            ("stopata", "stat.block"),
            ("stòpata", "stat.block"),
            ("palla rubata", "stat.steal"),
            ("palla rubato", "stat.steal"),
            ("perse", "stat.turnover"),
            ("perso", "stat.turnover"),
            ("passi", "stat.turnover"),
            ("paso", "stat.turnover"),
            ("doppio dribbling", "stat.turnover"),
            ("dopio dribbling", "stat.turnover"),
        ],
        substitutionKeywords: ["cambio", "sostituzione", "sostituisci", "entra"],
        commandEvents: [
            ("inizio", "event.period"),
            ("primo quarto", "event.period"),
            ("prossimo quarto", "event.period"),
            ("quarto concluso", "event.period"),
            ("pausa", "event.pause"),
            ("timeout", "event.pause"),
            ("continuare", "event.pause"),
            ("riprendere", "event.pause"),
            ("fine", "event.game_end"),
            ("fine partita", "event.game_end"),
            ("finito", "event.game_end"),
            ("terminato", "event.game_end"),
        ],
        fuzzyMap: [],
        surnamePinyinOverrides: [:],
        pinyinVariantRules: [],
        multiPronunciations: [:],
        useLevenshteinMatching: true,
        levenshteinThreshold: (short: 1, long: 2),
        useAnchorMatching: false,
        anchorWords: [],
        stealTargetRule: .init(prefixesToStrip: ["a "])
    )
}
