import Foundation

extension VoiceRulesData {

    static let japanese = VoiceRulesData(
        locale: "ja-JP",
        speechRecognizerLocale: "ja-JP",
        shotKeywords: [
            ShotKeywordData(keyword: "ツー", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "ツーポイント", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "ツ", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "2", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "スリー", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "スリーポイント", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "スリ", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "3", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "レイアップ", eventPrefix: "stat.layup"),
            ShotKeywordData(keyword: "レアップ", eventPrefix: "stat.layup"),
            ShotKeywordData(keyword: "レイアプ", eventPrefix: "stat.layup"),
            ShotKeywordData(keyword: "レアプ", eventPrefix: "stat.layup"),
            ShotKeywordData(keyword: "ミドル", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "ミドルレンジ", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "ミドレンジ", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "ペイント", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "インサイド", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "ポストアップ", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "ポスタップ", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "フリースロー", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "フリスロー", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "フリスロ", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "フリー", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "フリスル", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "ボーナス", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "ボナス", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "アンドワン", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "アンドワ", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "ワンプラスワン", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "パットバック", eventPrefix: "stat.putback"),
            ShotKeywordData(keyword: "パットバク", eventPrefix: "stat.putback"),
            ShotKeywordData(keyword: "putback", eventPrefix: "stat.putback"),
            ShotKeywordData(keyword: "ダンク", eventPrefix: "stat.dunk"),
            ShotKeywordData(keyword: "ダンクシュート", eventPrefix: "stat.dunk"),
            ShotKeywordData(keyword: "dunk", eventPrefix: "stat.dunk")
        ],
        madeStates: ["入った", "成功", "決めた", "決まった"],
        missedStates: ["外した", "入らない", "ミス", "失敗", "ブロック", "届かない", "はずれ", "ない", "ノー", "エアボール"],
        statEvents: [
            ["ファウル", "stat.foul"],
            ["ファール", "stat.foul"],
            ["ファル", "stat.foul"],
            ["リバウンド", "stat.rebound"],
            ["リバウン", "stat.rebound"],
            ["リバン", "stat.rebound"],
            ["オフェンスリバウンド", "stat.offensiveRebound"],
            ["オフェンスリバウン", "stat.offensiveRebound"],
            ["オフェンスリバン", "stat.offensiveRebound"],
            ["ディフェンスリバウンド", "stat.defensiveRebound"],
            ["ディフェンスリバウン", "stat.defensiveRebound"],
            ["ディフェンスリバン", "stat.defensiveRebound"],
            ["アシスト", "stat.assist"],
            ["アシト", "stat.assist"],
            ["アシス", "stat.assist"],
            ["ブロック", "stat.block"],
            ["ブロク", "stat.block"],
            ["ブロ", "stat.block"],
            ["スティール", "stat.steal"],
            ["スティル", "stat.steal"],
            ["スチール", "stat.steal"],
            ["ターンオーバー", "stat.turnover"],
            ["ターンオーバ", "stat.turnover"],
            ["タンオーバ", "stat.turnover"],
            ["トラベリング", "stat.turnover"],
            ["トラベリン", "stat.turnover"],
            ["バイオレーション", "stat.turnover"],
            ["ダブルドリブル", "stat.turnover"],
            ["ダブドリブル", "stat.turnover"]
        ],
        substitutionKeywords: ["交代", "選手交代", "チェンジ", "入れ替え"],
        commandEvents: [
            ["開始", "event.period"],
            ["スタート", "event.period"],
            ["第1クオーター", "event.period"],
            ["次のクオーター", "event.period"],
            ["クオーターエンド", "event.period"],
            ["一時停止", "event.pause"],
            ["タイムアウト", "event.pause"],
            ["ストップ", "event.pause"],
            ["休憩", "event.pause"],
            ["再開", "event.pause"],
            ["リスタート", "event.pause"],
            ["続ける", "event.pause"],
            ["終了", "event.game_end"],
            ["試合終了", "event.game_end"],
            ["ゲーム終了", "event.game_end"],
            ["終わり", "event.game_end"],
            ["ファイナル", "event.game_end"],
            ["元に戻す", "event.undo"],
            ["アンドゥ", "event.undo"],
            ["やり直す", "event.redo"],
            ["リドゥ", "event.redo"]
        ],
        fuzzyMap: nil,
        surnamePinyinOverrides: nil,
        pinyinVariantRules: nil,
        multiPronunciations: nil,
        useLevenshteinMatching: true,
        levenshteinThresholdShort: 1,
        levenshteinThresholdLong: 2,
        useAnchorMatching: false,
        anchorWords: [],
        stealTargetRule: StealTargetRuleData(
                    extractFrom: "leftTextAfterPlayer",
                    suffixesToStrip: ["から"],
                    segmentParticles: ["が", "から"]
                )
    )
}