import Foundation

extension VoiceRules {
    static let german = VoiceRules(
        locale: Locale(identifier: "de-DE"),
        speechRecognizerLocale: Locale(identifier: "de-DE"),
        shotKeywords: [
            .init(keyword: "zwei", eventPrefix: "stat.two"),
            .init(keyword: "zwei punkte", eventPrefix: "stat.two"),
            .init(keyword: "zvei", eventPrefix: "stat.two"),
            .init(keyword: "2", eventPrefix: "stat.two"),
            .init(keyword: "drei", eventPrefix: "stat.three"),
            .init(keyword: "drei punkte", eventPrefix: "stat.three"),
            .init(keyword: "dreier", eventPrefix: "stat.three"),
            .init(keyword: "dreyer", eventPrefix: "stat.three"),
            .init(keyword: "3", eventPrefix: "stat.three"),
            .init(keyword: "layup", eventPrefix: "stat.layup"),
            .init(keyword: "lay up", eventPrefix: "stat.layup"),
            .init(keyword: "mitteldistanz", eventPrefix: "stat.midRange"),
            .init(keyword: "mittlere distanz", eventPrefix: "stat.midRange"),
            .init(keyword: "mittel distanz", eventPrefix: "stat.midRange"),
            .init(keyword: "korb", eventPrefix: "stat.paint"),
            .init(keyword: "korb nähe", eventPrefix: "stat.paint"),
            .init(keyword: "korbnähe", eventPrefix: "stat.paint"),
            .init(keyword: "freiwurf", eventPrefix: "stat.freeThrow"),
            .init(keyword: "frei wurf", eventPrefix: "stat.freeThrow"),
            .init(keyword: "freivurf", eventPrefix: "stat.freeThrow"),
            .init(keyword: "bonus", eventPrefix: "stat.bonus"),
            .init(keyword: "and one", eventPrefix: "stat.bonus"),
            .init(keyword: "and won", eventPrefix: "stat.bonus"),
        ],
        madeStates: ["getroffen", "drin", "gut", "rein", "erfolg"],
        missedStates: ["verfehlt", "daneben", "blockiert", "nicht", "vorbei", "nein", "miss"],
        statEvents: [
            ("foul", "stat.foul"),
            ("faul", "stat.foul"),
            ("fowl", "stat.foul"),
            ("rebound", "stat.rebound"),
            ("ribaund", "stat.rebound"),
            ("abpraller", "stat.rebound"),
            ("abpraler", "stat.rebound"),
            ("assist", "stat.assist"),
            ("asist", "stat.assist"),
            ("vorlage", "stat.assist"),
            ("forlage", "stat.assist"),
            ("block", "stat.block"),
            ("blok", "stat.block"),
            ("bloc", "stat.block"),
            ("steal", "stat.steal"),
            ("stil", "stat.steal"),
            ("diebstahl", "stat.steal"),
            ("diepstahl", "stat.steal"),
            ("turnover", "stat.turnover"),
            ("ballverlust", "stat.turnover"),
            ("ball verlust", "stat.turnover"),
            ("schrittfehler", "stat.turnover"),
            ("schritt fehler", "stat.turnover"),
        ],
        substitutionKeywords: ["wechsel", "auswechslung", "ersetzen", "rein", "raus"],
        commandEvents: [
            ("start", "event.period"),
            ("sprungball", "event.period"),
            ("tip off", "event.period"),
            ("erstes viertel", "event.period"),
            ("nächstes viertel", "event.period"),
            ("viertel um", "event.period"),
            ("pause", "event.pause"),
            ("auszeit", "event.pause"),
            ("weiter", "event.pause"),
            ("weiterspielen", "event.pause"),
            ("ende", "event.game_end"),
            ("spielende", "event.game_end"),
            ("schluss", "event.game_end"),
            ("fertig", "event.game_end"),
        ],
        fuzzyMap: [],
        surnamePinyinOverrides: [:],
        pinyinVariantRules: [],
        useLevenshteinMatching: true,
        levenshteinThreshold: (short: 1, long: 2),
        useAnchorMatching: false,
        anchorWords: []
    )
}
