import Foundation

extension VoiceRules {
    static let spanish = VoiceRules(
        locale: Locale(identifier: "es-ES"),
        speechRecognizerLocale: Locale(identifier: "es-ES"),
        shotKeywords: [
            .init(keyword: "dos", eventPrefix: "stat.two"),
            .init(keyword: "dos puntos", eventPrefix: "stat.two"),
            .init(keyword: "do", eventPrefix: "stat.two"),
            .init(keyword: "2", eventPrefix: "stat.two"),
            .init(keyword: "tres", eventPrefix: "stat.three"),
            .init(keyword: "tres puntos", eventPrefix: "stat.three"),
            .init(keyword: "tre", eventPrefix: "stat.three"),
            .init(keyword: "treh", eventPrefix: "stat.three"),
            .init(keyword: "3", eventPrefix: "stat.three"),
            .init(keyword: "bandeja", eventPrefix: "stat.layup"),
            .init(keyword: "media", eventPrefix: "stat.midRange"),
            .init(keyword: "media distancia", eventPrefix: "stat.midRange"),
            .init(keyword: "pintura", eventPrefix: "stat.paint"),
            .init(keyword: "interior", eventPrefix: "stat.paint"),
            .init(keyword: "tiro libre", eventPrefix: "stat.freeThrow"),
            .init(keyword: "libre", eventPrefix: "stat.freeThrow"),
            .init(keyword: "bonus", eventPrefix: "stat.bonus"),
            .init(keyword: "y uno", eventPrefix: "stat.bonus"),
        ],
        madeStates: [],
        missedStates: ["fallado", "fuera", "bloqueado", "perdido"],
        statEvents: [
            ("falta", "stat.foul"),
            ("farta", "stat.foul"),
            ("rebote", "stat.rebound"),
            ("rebote ofensivo", "stat.rebound"),
            ("rebote defensivo", "stat.rebound"),
            ("asistencia", "stat.assist"),
            ("bloqueo", "stat.block"),
            ("tapón", "stat.block"),
            ("tapon", "stat.block"),
            ("robo", "stat.steal"),
            ("perdida", "stat.turnover"),
            ("pasos", "stat.turnover"),
            ("doble dribble", "stat.turnover"),
        ],
        substitutionKeywords: ["cambio", "sustitución", "reemplazo", "sustituye"],
        commandEvents: [
            ("inicio", "event.period"),
            ("primer cuarto", "event.period"),
            ("pausa", "event.pause"),
            ("tiempo muerto", "event.pause"),
            ("continuar", "event.pause"),
            ("reanudar", "event.pause"),
            ("final", "event.game_end"),
            ("fin del partido", "event.game_end"),
        ],
        fuzzyMap: [],
        surnamePinyinOverrides: [:]
    )
}
