import Foundation

extension VoiceRulesData {
    static let english = VoiceRulesData(
        locale: "en-US",
        speechRecognizerLocale: "en-US",
        shotKeywords: [
            ShotKeywordData(keyword: "two", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "two pointer", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "too", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "2", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "2 pointer", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "three free throw", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "three", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "three pointer", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "3", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "3 pointer", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "trey", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "tree", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "layup", eventPrefix: "stat.layup"),
            ShotKeywordData(keyword: "lay up", eventPrefix: "stat.layup"),
            ShotKeywordData(keyword: "mid", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "mid range", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "jumper", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "jump shot", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "pull up", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "paint", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "inside", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "post up", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "free throw", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "foul shot", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "fowl shot", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "faul shot", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "four shot", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "free through", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "free thru", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "free", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "bonus", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "and one", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "putback", eventPrefix: "stat.putback"),
            ShotKeywordData(keyword: "put back", eventPrefix: "stat.putback"),
            ShotKeywordData(keyword: "dunk", eventPrefix: "stat.dunk"),
            ShotKeywordData(keyword: "dunk shot", eventPrefix: "stat.dunk"),
            ShotKeywordData(keyword: "slam dunk", eventPrefix: "stat.dunk"),
            ShotKeywordData(keyword: "slam", eventPrefix: "stat.dunk")
        ],
        madeStates: ["got", "get"],
        missedStates: ["missed", "no", "miss", "not", "know", "blocked", "out", "airball", "brick", "short"],
        statEvents: [
            ["foul", "stat.foul"],
            ["fouls", "stat.foul"],
            ["fowl", "stat.foul"],
            ["faul", "stat.foul"],
            ["four", "stat.foul"],
            ["force", "stat.foul"],
            ["forces", "stat.foul"],
            ["reach", "stat.foul"],
            ["hack", "stat.foul"],
            ["rebound", "stat.rebound"],
            ["rebounds", "stat.rebound"],
            ["board", "stat.rebound"],
            ["boards", "stat.rebound"],
            ["glass", "stat.rebound"],
            ["rebaund", "stat.rebound"],
            ["ribaund", "stat.rebound"],
            ["rebo", "stat.rebound"],
            ["offensive rebound", "stat.offensiveRebound"],
            ["offensive rebaund", "stat.offensiveRebound"],
            ["offensive ribaund", "stat.offensiveRebound"],
            ["defensive rebound", "stat.defensiveRebound"],
            ["defensive rebaund", "stat.defensiveRebound"],
            ["defensive ribaund", "stat.defensiveRebound"],
            ["assist", "stat.assist"],
            ["a sister", "stat.assist"],
            ["dime", "stat.assist"],
            ["block", "stat.block"],
            ["bloc", "stat.block"],
            ["swat", "stat.block"],
            ["steal", "stat.steal"],
            ["steel", "stat.steal"],
            ["takeaway", "stat.steal"],
            ["turnover", "stat.turnover"],
            ["turn over", "stat.turnover"],
            ["travel", "stat.turnover"],
            ["walk", "stat.turnover"],
            ["violation", "stat.turnover"],
            ["carry", "stat.turnover"],
            ["double dribble", "stat.turnover"]
        ],
        substitutionKeywords: ["sub", "substitution", "substitute", "replace", "swap", "change", "switch", "in for"],
        commandEvents: [
            ["start", "event.period"],
            ["begin", "event.period"],
            ["tip off", "event.period"],
            ["jump ball", "event.period"],
            ["next quarter", "event.period"],
            ["quarter done", "event.period"],
            ["quarter down", "event.period"],
            ["quarter end", "event.period"],
            ["pause", "event.pause"],
            ["timeout", "event.pause"],
            ["stop", "event.pause"],
            ["resume", "event.pause"],
            ["continue", "event.pause"],
            ["unpause", "event.pause"],
            ["play", "event.pause"],
            ["end", "event.game_end"],
            ["finish", "event.game_end"],
            ["game over", "event.game_end"],
            ["final", "event.game_end"],
            ["undo", "event.undo"],
            ["redo", "event.redo"]
        ],
        fuzzyMap: nil,
        surnamePinyinOverrides: nil,
        pinyinVariantRules: nil,
        multiPronunciations: nil,
        useLevenshteinMatching: true,
        levenshteinThresholdShort: 1,
        levenshteinThresholdLong: 3,
        useAnchorMatching: true,
        anchorWords: ["made", "got", "get", "missed", "miss", "no", "not", "know"],
        stealTargetRule: StealTargetRuleData(
            prefixesToStrip: ["from "]
        )
    )
}
