import Foundation

extension VoiceRulesData {

    static let chineseSimplified = VoiceRulesData(
        locale: "zh-CN",
        speechRecognizerLocale: "zh-CN",
        shotKeywords: [
            ShotKeywordData(keyword: "两分", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "2分", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "投篮", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "三分", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "3分", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "上篮", eventPrefix: "stat.layup"),
            ShotKeywordData(keyword: "shang lai", eventPrefix: "stat.layup"),
            ShotKeywordData(keyword: "中投", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "中距离", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "篮下", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "内线", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "na xia", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "罚球", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "罚篮", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "发球", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "加罚", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "山分", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "散分", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "三份", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "法球", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "加法", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "补篮", eventPrefix: "stat.putback"),
            ShotKeywordData(keyword: "补进", eventPrefix: "stat.putback"),
            ShotKeywordData(keyword: "bu lan", eventPrefix: "stat.putback"),
            ShotKeywordData(keyword: "bu jin", eventPrefix: "stat.putback"),
            ShotKeywordData(keyword: "不来", eventPrefix: "stat.putback"),
            ShotKeywordData(keyword: "扣篮", eventPrefix: "stat.dunk"),
            ShotKeywordData(keyword: "扣进", eventPrefix: "stat.dunk"),
            ShotKeywordData(keyword: "kou lan", eventPrefix: "stat.dunk"),
            ShotKeywordData(keyword: "kou jin", eventPrefix: "stat.dunk")
        ],
        madeStates: ["命中", "进", "得分", "成功"],
        missedStates: ["未中", "没中", "不中", "不进", "没进", "打铁"],
        statEvents: [
            ["犯规", "stat.foul"],
            ["篮板", "stat.rebound"],
            ["板", "stat.rebound"],
            ["nan ban", "stat.rebound"],
            ["前场板", "stat.offensiveRebound"],
            ["前场篮板", "stat.offensiveRebound"],
            ["全场板", "stat.offensiveRebound"],
            ["全场篮板", "stat.offensiveRebound"],
            ["quan chang ban", "stat.offensiveRebound"],
            ["quan chang lan ban", "stat.offensiveRebound"],
            ["qian chang ba", "stat.offensiveRebound"],
            ["quan chang ba", "stat.offensiveRebound"],
            ["qian chang ban", "stat.offensiveRebound"],
            ["qian chang lan ban", "stat.offensiveRebound"],
            ["后场板", "stat.defensiveRebound"],
            ["后场篮板", "stat.defensiveRebound"],
            ["hou chang ban", "stat.defensiveRebound"],
            ["hou chang lan ban", "stat.defensiveRebound"],
            ["hou chang ba", "stat.defensiveRebound"],
            ["抢板", "stat.rebound"],
            ["助攻", "stat.assist"],
            ["盖帽", "stat.block"],
            ["封盖", "stat.block"],
            ["抢断", "stat.steal"],
            ["断球", "stat.steal"],
            ["失误", "stat.turnover"],
            ["方归", "stat.foul"],
            ["lan ban", "stat.rebound"],
            ["走步", "stat.turnover"],
            ["违例", "stat.turnover"]
        ],
        substitutionKeywords: ["换人", "替换", "换上", "换下", "换"],
        commandEvents: [
            ["开始", "event.period"],
            ["第一节", "event.period"],
            ["第1节", "event.period"],
            ["第二节", "event.period"],
            ["第2节", "event.period"],
            ["第三节", "event.period"],
            ["第3节", "event.period"],
            ["第四节", "event.period"],
            ["第4节", "event.period"],
            ["下一节", "event.period"],
            ["结束本节", "event.period"],
            ["节结束", "event.period"],
            ["暂停", "event.pause"],
            ["停表", "event.pause"],
            ["继续", "event.pause"],
            ["继续比赛", "event.pause"],
            ["比赛继续", "event.pause"],
            ["撤销", "event.undo"],
            ["撤回", "event.undo"],
            ["重做", "event.redo"],
            ["恢复", "event.redo"]
        ],
        fuzzyMap: [
            ["zh", "z"],
            ["ch", "c"],
            ["sh", "s"],
            ["r", "l"],
            ["eng", "en"],
            ["ing", "in"],
            ["ang", "an"]
        ],
        surnamePinyinOverrides: [
            "曾": ["zeng"],
            "单": ["shan"],
            "朴": ["piao"],
            "解": ["xie"],
            "区": ["ou"],
            "仇": ["qiu"],
            "盖": ["ge"],
            "查": ["zha"],
            "华": ["hua"],
            "缪": ["miao"],
            "覃": ["qin"],
            "芮": ["rui"],
            "逄": ["pang"]
        ],
        pinyinVariantRules: [
            ["zh", "z"],
            ["z", "zh"],
            ["ch", "c"],
            ["c", "ch"],
            ["sh", "s"],
            ["s", "sh"],
            ["r", "l"],
            ["l", "r"],
            ["n", "l"],
            ["l", "n"],
            ["m", "n"],
            ["n", "m"],
            ["eng", "en"],
            ["en", "eng"],
            ["ing", "in"],
            ["in", "ing"],
            ["ang", "an"],
            ["an", "ang"],
            ["ian", "uan"],
            ["uan", "ian"]
        ],
        multiPronunciations: [
            "长": ["chang", "zhang"],
            "行": ["xing", "hang"],
            "乐": ["le", "yue"],
            "传": ["chuan", "zhuan"],
            "重": ["zhong", "chong"],
            "的": ["de", "di"],
            "地": ["de", "di"]
        ],
        useLevenshteinMatching: false,
        levenshteinThresholdShort: 1,
        levenshteinThresholdLong: 2,
        useAnchorMatching: false,
        anchorWords: [],
        stealTargetRule: nil
    )
}