import Foundation

extension VoiceRules {
    static let german = VoiceRules(
        locale: Locale(identifier: "de-DE"),
        speechRecognizerLocale: Locale(identifier: "de-DE"),
        shotKeywords: [
            .init(keyword: "zwei", eventPrefix: "stat.two"),
            .init(keyword: "zwei punkte", eventPrefix: "stat.two"),
            .init(keyword: "2", eventPrefix: "stat.two"),
            .init(keyword: "drei", eventPrefix: "stat.three"),
            .init(keyword: "drei punkte", eventPrefix: "stat.three"),
            .init(keyword: "dreier", eventPrefix: "stat.three"),
            .init(keyword: "3", eventPrefix: "stat.three"),
            .init(keyword: "layup", eventPrefix: "stat.layup"),
            .init(keyword: "mitteldistanz", eventPrefix: "stat.midRange"),
            .init(keyword: "mittlerer", eventPrefix: "stat.midRange"),
            .init(keyword: "korb", eventPrefix: "stat.paint"),
            .init(keyword: "korb nähe", eventPrefix: "stat.paint"),
            .init(keyword: "freiwurf", eventPrefix: "stat.freeThrow"),
            .init(keyword: "bonus", eventPrefix: "stat.bonus"),
            .init(keyword: "and one", eventPrefix: "stat.bonus"),
        ],
        madeStates: ["getroffen", "drin", "gut", "rein"],
        missedStates: ["verfehlt", "daneben", "blockiert", "nicht", "vorbei"],
        statEvents: [
            ("foul", "stat.foul"),
            ("rebound", "stat.rebound"),
            ("abpraller", "stat.rebound"),
            ("assist", "stat.assist"),
            ("vorlage", "stat.assist"),
            ("block", "stat.block"),
            ("steal", "stat.steal"),
            ("diebstahl", "stat.steal"),
            ("turnover", "stat.turnover"),
            ("ballverlust", "stat.turnover"),
            ("schrittfehler", "stat.turnover"),
        ],
        substitutionKeywords: ["wechsel", "auswechslung", "ersetzen", "rein", "raus"],
        commandEvents: [
            ("start", "event.period"),
            ("anpfiff", "event.period"),
            ("erste viertel", "event.period"),
            ("pause", "event.pause"),
            ("auszeit", "event.pause"),
            ("weiter", "event.pause"),
            ("weiterspielen", "event.pause"),
            ("ende", "event.game_end"),
            ("spielende", "event.game_end"),
            ("schluss", "event.game_end"),
        ],
        fuzzyMap: [],
        surnamePinyinOverrides: [:]
    )
}
