import Foundation

extension VoiceRules {
    static let traditionalChinese = VoiceRules(
        locale: Locale(identifier: "zh-Hant-TW"),
        speechRecognizerLocale: Locale(identifier: "zh-TW"),
        shotKeywords: [
            .init(keyword: "兩分", eventPrefix: "stat.two"),
            .init(keyword: "2分", eventPrefix: "stat.two"),
            .init(keyword: "三分", eventPrefix: "stat.three"),
            .init(keyword: "3分", eventPrefix: "stat.three"),
            .init(keyword: "上籃", eventPrefix: "stat.layup"),
            .init(keyword: "中投", eventPrefix: "stat.midRange"),
            .init(keyword: "中距離", eventPrefix: "stat.midRange"),
            .init(keyword: "籃下", eventPrefix: "stat.paint"),
            .init(keyword: "內線", eventPrefix: "stat.paint"),
            .init(keyword: "罰球", eventPrefix: "stat.freeThrow"),
            .init(keyword: "罰籃", eventPrefix: "stat.freeThrow"),
            .init(keyword: "加罰", eventPrefix: "stat.bonus"),
        ],
        madeStates: ["命中", "進", "得分", "成功"],
        missedStates: ["未中", "沒中", "不中", "不進", "沒進"],
        statEvents: [
            ("犯規", "stat.foul"),
            ("籃板", "stat.rebound"),
            ("板", "stat.rebound"),
            ("前場板", "stat.rebound"),
            ("後場板", "stat.rebound"),
            ("搶板", "stat.rebound"),
            ("助攻", "stat.assist"),
            ("蓋帽", "stat.block"),
            ("封蓋", "stat.block"),
            ("搶斷", "stat.steal"),
            ("斷球", "stat.steal"),
            ("失誤", "stat.turnover"),
            ("走步", "stat.turnover"),
            ("違例", "stat.turnover"),
        ],
        substitutionKeywords: ["換人", "替換", "換上", "換下", "換"],
        commandEvents: [
            ("開始", "event.period"),
            ("第一節", "event.period"),
            ("第1節", "event.period"),
            ("第二節", "event.period"),
            ("第2節", "event.period"),
            ("第三節", "event.period"),
            ("第3節", "event.period"),
            ("第四節", "event.period"),
            ("第4節", "event.period"),
            ("下一節", "event.period"),
            ("暫停", "event.pause"),
            ("停表", "event.pause"),
            ("繼續", "event.pause"),
            ("繼續比賽", "event.pause"),
            ("比賽繼續", "event.pause"),
        ],
        fuzzyMap: [
            ("zh", "z"), ("ch", "c"), ("sh", "s"),
            ("r", "l"),
            ("eng", "en"), ("ing", "in"), ("ang", "an"),
        ]
    )
}
