import Foundation

extension VoiceRules {
    static let french = VoiceRules(
        locale: Locale(identifier: "fr-FR"),
        speechRecognizerLocale: Locale(identifier: "fr-FR"),
        shotKeywords: [
            .init(keyword: "deux", eventPrefix: "stat.two"),
            .init(keyword: "deux points", eventPrefix: "stat.two"),
            .init(keyword: "2", eventPrefix: "stat.two"),
            .init(keyword: "trois", eventPrefix: "stat.three"),
            .init(keyword: "trois points", eventPrefix: "stat.three"),
            .init(keyword: "3", eventPrefix: "stat.three"),
            .init(keyword: "lay-up", eventPrefix: "stat.layup"),
            .init(keyword: "couche", eventPrefix: "stat.layup"),
            .init(keyword: "mi-distance", eventPrefix: "stat.midRange"),
            .init(keyword: "moyenne distance", eventPrefix: "stat.midRange"),
            .init(keyword: "intérieur", eventPrefix: "stat.paint"),
            .init(keyword: "lancer franc", eventPrefix: "stat.freeThrow"),
            .init(keyword: "lancer", eventPrefix: "stat.freeThrow"),
            .init(keyword: "panier", eventPrefix: "stat.two"),
            .init(keyword: "bonus", eventPrefix: "stat.bonus"),
            .init(keyword: "et un", eventPrefix: "stat.bonus"),
        ],
        madeStates: ["marqué", "dedans", "dans", "bon", "réussi"],
        missedStates: ["raté", "dehors", "loupé", "contré", "manqué", "bloqué"],
        statEvents: [
            ("faute", "stat.foul"),
            ("rebond", "stat.rebound"),
            ("rebond offensif", "stat.rebound"),
            ("rebond défensif", "stat.rebound"),
            ("passe", "stat.assist"),
            ("passe décisive", "stat.assist"),
            ("contre", "stat.block"),
            ("interception", "stat.steal"),
            ("perte de balle", "stat.turnover"),
            ("marcher", "stat.turnover"),
            ("marche", "stat.turnover"),
            ("double dribble", "stat.turnover"),
        ],
        substitutionKeywords: ["remplacement", "changement", "substitution", "remplace"],
        commandEvents: [
            ("début", "event.period"),
            ("coup d'envoi", "event.period"),
            ("premier quart", "event.period"),
            ("premier quart-temps", "event.period"),
            ("pause", "event.pause"),
            ("arrêter", "event.pause"),
            ("temps mort", "event.pause"),
            ("continuer", "event.pause"),
            ("reprise", "event.pause"),
            ("reprendre", "event.pause"),
            ("fin", "event.game_end"),
            ("fin du match", "event.game_end"),
        ],
        fuzzyMap: []
    )
}
