import Foundation

extension VoiceRules {
    static let japanese = VoiceRules(
        locale: Locale(identifier: "ja-JP"),
        speechRecognizerLocale: Locale(identifier: "ja-JP"),
        shotKeywords: [
            .init(keyword: "ツー", eventPrefix: "stat.two"),
            .init(keyword: "ツーポイント", eventPrefix: "stat.two"),
            .init(keyword: "ツ", eventPrefix: "stat.two"),
            .init(keyword: "2", eventPrefix: "stat.two"),
            .init(keyword: "スリー", eventPrefix: "stat.three"),
            .init(keyword: "スリーポイント", eventPrefix: "stat.three"),
            .init(keyword: "スリ", eventPrefix: "stat.three"),
            .init(keyword: "3", eventPrefix: "stat.three"),
            .init(keyword: "レイアップ", eventPrefix: "stat.layup"),
            .init(keyword: "レアップ", eventPrefix: "stat.layup"),
            .init(keyword: "レイアプ", eventPrefix: "stat.layup"),
            .init(keyword: "レアプ", eventPrefix: "stat.layup"),
            .init(keyword: "ミドル", eventPrefix: "stat.midRange"),
            .init(keyword: "ミドルレンジ", eventPrefix: "stat.midRange"),
            .init(keyword: "ミドレンジ", eventPrefix: "stat.midRange"),
            .init(keyword: "ペイント", eventPrefix: "stat.paint"),
            .init(keyword: "インサイド", eventPrefix: "stat.paint"),
            .init(keyword: "ポストアップ", eventPrefix: "stat.paint"),
            .init(keyword: "ポスタップ", eventPrefix: "stat.paint"),
            .init(keyword: "フリースロー", eventPrefix: "stat.freeThrow"),
            .init(keyword: "フリスロー", eventPrefix: "stat.freeThrow"),
            .init(keyword: "フリスロ", eventPrefix: "stat.freeThrow"),
            .init(keyword: "フリー", eventPrefix: "stat.freeThrow"),
            .init(keyword: "フリスル", eventPrefix: "stat.freeThrow"),
            .init(keyword: "ボーナス", eventPrefix: "stat.bonus"),
            .init(keyword: "ボナス", eventPrefix: "stat.bonus"),
            .init(keyword: "アンドワン", eventPrefix: "stat.bonus"),
            .init(keyword: "アンドワ", eventPrefix: "stat.bonus"),
            .init(keyword: "ワンプラスワン", eventPrefix: "stat.bonus"),
        ],
        madeStates: ["入った", "成功", "決めた", "決まった"],
        missedStates: ["外した", "入らない", "ミス", "失敗", "ブロック", "届かない", "はずれ"],
        statEvents: [
            ("ファウル", "stat.foul"),
            ("ファール", "stat.foul"),
            ("ファル", "stat.foul"),
            ("リバウンド", "stat.rebound"),
            ("リバウン", "stat.rebound"),
            ("リバン", "stat.rebound"),
            ("オフェンスリバウンド", "stat.offensiveRebound"),
            ("オフェンスリバウン", "stat.offensiveRebound"),
            ("オフェンスリバン", "stat.offensiveRebound"),
            ("ディフェンスリバウンド", "stat.defensiveRebound"),
            ("ディフェンスリバウン", "stat.defensiveRebound"),
            ("ディフェンスリバン", "stat.defensiveRebound"),
            ("アシスト", "stat.assist"),
            ("アシト", "stat.assist"),
            ("アシス", "stat.assist"),
            ("ブロック", "stat.block"),
            ("ブロク", "stat.block"),
            ("ブロ", "stat.block"),
            ("スティール", "stat.steal"),
            ("スティル", "stat.steal"),
            ("スチール", "stat.steal"),
            ("ターンオーバー", "stat.turnover"),
            ("ターンオーバ", "stat.turnover"),
            ("タンオーバ", "stat.turnover"),
            ("トラベリング", "stat.turnover"),
            ("トラベリン", "stat.turnover"),
            ("バイオレーション", "stat.turnover"),
            ("ダブルドリブル", "stat.turnover"),
            ("ダブドリブル", "stat.turnover"),
        ],
        substitutionKeywords: ["交代", "選手交代", "チェンジ", "入れ替え"],
        commandEvents: [
            ("開始", "event.period"),
            ("スタート", "event.period"),
            ("第1クオーター", "event.period"),
            ("次のクオーター", "event.period"),
            ("次", "event.period"),
            ("クオーターエンド", "event.period"),
            ("一時停止", "event.pause"),
            ("タイムアウト", "event.pause"),
            ("休憩", "event.pause"),
            ("再開", "event.pause"),
            ("リスタート", "event.pause"),
            ("続ける", "event.pause"),
            ("終了", "event.game_end"),
            ("試合終了", "event.game_end"),
            ("ゲーム終了", "event.game_end"),
            ("終わり", "event.game_end"),
            ("ファイナル", "event.game_end"),
        ],
        fuzzyMap: [],
        surnamePinyinOverrides: [:],
        pinyinVariantRules: [],
        useLevenshteinMatching: true,
        levenshteinThreshold: (short: 1, long: 2),
        useAnchorMatching: false,
        anchorWords: [],
        stealTargetRule: .init(
            extractFrom: .leftTextAfterPlayer,
            suffixesToStrip: ["から"],
            segmentParticles: ["が", "から"]
        )
    )
}
