import Foundation

extension VoiceRules {
    static let russian = VoiceRules(
        locale: Locale(identifier: "ru-RU"),
        speechRecognizerLocale: Locale(identifier: "ru-RU"),
        shotKeywords: [
            .init(keyword: "два", eventPrefix: "stat.two"),
            .init(keyword: "двушка", eventPrefix: "stat.two"),
            .init(keyword: "дла", eventPrefix: "stat.two"),
            .init(keyword: "два очка", eventPrefix: "stat.two"),
            .init(keyword: "2", eventPrefix: "stat.two"),
            .init(keyword: "три", eventPrefix: "stat.three"),
            .init(keyword: "трёшка", eventPrefix: "stat.three"),
            .init(keyword: "тли", eventPrefix: "stat.three"),
            .init(keyword: "трешка", eventPrefix: "stat.three"),
            .init(keyword: "3", eventPrefix: "stat.three"),
            .init(keyword: "лей-ап", eventPrefix: "stat.layup"),
            .init(keyword: "лей ап", eventPrefix: "stat.layup"),
            .init(keyword: "лэй-ап", eventPrefix: "stat.layup"),
            .init(keyword: "средний", eventPrefix: "stat.midRange"),
            .init(keyword: "средний бросок", eventPrefix: "stat.midRange"),
            .init(keyword: "краска", eventPrefix: "stat.paint"),
            .init(keyword: "изнутри", eventPrefix: "stat.paint"),
            .init(keyword: "из под кольца", eventPrefix: "stat.paint"),
            .init(keyword: "штрафной", eventPrefix: "stat.freeThrow"),
            .init(keyword: "штрафной бросок", eventPrefix: "stat.freeThrow"),
            .init(keyword: "штрафный", eventPrefix: "stat.freeThrow"),
            .init(keyword: "бонус", eventPrefix: "stat.bonus"),
            .init(keyword: "бонас", eventPrefix: "stat.bonus"),
        ],
        madeStates: ["попал", "забил", "есть", "удачно", "зашёл"],
        missedStates: ["промах", "мимо", "заблокировали", "не попал", "нет", "мимо кольца"],
        statEvents: [
            ("фол", "stat.foul"),
            ("фал", "stat.foul"),
            ("вал", "stat.foul"),
            ("фаул", "stat.foul"),
            ("подбор", "stat.rebound"),
            ("потбор", "stat.rebound"),
            ("падбор", "stat.rebound"),
            ("подбор в нападении", "stat.offensiveRebound"),
            ("потбор в нападении", "stat.offensiveRebound"),
            ("падбор в нападении", "stat.offensiveRebound"),
            ("подбор в защите", "stat.defensiveRebound"),
            ("потбор в защите", "stat.defensiveRebound"),
            ("падбор в защите", "stat.defensiveRebound"),
            ("передача", "stat.assist"),
            ("ассист", "stat.assist"),
            ("асист", "stat.assist"),
            ("пас", "stat.assist"),
            ("блок", "stat.block"),
            ("блок-шот", "stat.block"),
            ("блок шот", "stat.block"),
            ("плок", "stat.block"),
            ("перехват", "stat.steal"),
            ("пирихват", "stat.steal"),
            ("потеря", "stat.turnover"),
            ("патеря", "stat.turnover"),
            ("пробежка", "stat.turnover"),
            ("прабежка", "stat.turnover"),
            ("нарушение", "stat.turnover"),
            ("нарушенье", "stat.turnover"),
        ],
        substitutionKeywords: ["замена", "меняем", "заменить"],
        commandEvents: [
            ("начало", "event.period"),
            ("старт", "event.period"),
            ("первая четверть", "event.period"),
            ("следующая четверть", "event.period"),
            ("четверть завершена", "event.period"),
            ("пауза", "event.pause"),
            ("тайм-аут", "event.pause"),
            ("продолжить", "event.pause"),
            ("конец", "event.game_end"),
            ("конец игры", "event.game_end"),
            ("финал", "event.game_end"),
            ("закончили", "event.game_end"),
        ],
        fuzzyMap: [],
        surnamePinyinOverrides: [:],
        pinyinVariantRules: [],
        multiPronunciations: [:],
        useLevenshteinMatching: true,
        levenshteinThreshold: (short: 1, long: 2),
        useAnchorMatching: false,
        anchorWords: [],
        stealTargetRule: .init(prefixesToStrip: ["у "])
    )
}
