import Foundation

extension VoiceRules {
    static let spanish = VoiceRules(
        locale: Locale(identifier: "es-ES"),
        speechRecognizerLocale: Locale(identifier: "es-ES"),
        shotKeywords: [
            .init(keyword: "dos", eventPrefix: "stat.two"),
            .init(keyword: "dos puntos", eventPrefix: "stat.two"),
            .init(keyword: "do", eventPrefix: "stat.two"),
            .init(keyword: "doz", eventPrefix: "stat.two"),
            .init(keyword: "2", eventPrefix: "stat.two"),
            .init(keyword: "tres", eventPrefix: "stat.three"),
            .init(keyword: "tres puntos", eventPrefix: "stat.three"),
            .init(keyword: "tre", eventPrefix: "stat.three"),
            .init(keyword: "treh", eventPrefix: "stat.three"),
            .init(keyword: "trez", eventPrefix: "stat.three"),
            .init(keyword: "3", eventPrefix: "stat.three"),
            .init(keyword: "bandeja", eventPrefix: "stat.layup"),
            .init(keyword: "bandecha", eventPrefix: "stat.layup"),
            .init(keyword: "media", eventPrefix: "stat.midRange"),
            .init(keyword: "media distancia", eventPrefix: "stat.midRange"),
            .init(keyword: "media distansia", eventPrefix: "stat.midRange"),
            .init(keyword: "pintura", eventPrefix: "stat.paint"),
            .init(keyword: "interior", eventPrefix: "stat.paint"),
            .init(keyword: "tiro libre", eventPrefix: "stat.freeThrow"),
            .init(keyword: "tiro libra", eventPrefix: "stat.freeThrow"),
            .init(keyword: "libre", eventPrefix: "stat.freeThrow"),
            .init(keyword: "libra", eventPrefix: "stat.freeThrow"),
            .init(keyword: "bonus", eventPrefix: "stat.bonus"),
            .init(keyword: "y uno", eventPrefix: "stat.bonus"),
            .init(keyword: "i uno", eventPrefix: "stat.bonus"),
        ],
        madeStates: ["anotó", "entró", "metió", "canasta", "bueno"],
        missedStates: ["fallado", "fuera", "bloqueado", "perdido", "no", "fallo", "aire"],
        statEvents: [
            ("falta", "stat.foul"),
            ("farta", "stat.foul"),
            ("faldo", "stat.foul"),
            ("rebote", "stat.rebound"),
            ("revote", "stat.rebound"),
            ("rebota", "stat.rebound"),
            ("rebote ofensivo", "stat.offensiveRebound"),
            ("revote ofensivo", "stat.offensiveRebound"),
            ("rebota ofensivo", "stat.offensiveRebound"),
            ("rebote defensivo", "stat.defensiveRebound"),
            ("revote defensivo", "stat.defensiveRebound"),
            ("rebota defensivo", "stat.defensiveRebound"),
            ("asistencia", "stat.assist"),
            ("asistensa", "stat.assist"),
            ("asiste", "stat.assist"),
            ("bloqueo", "stat.block"),
            ("bloquel", "stat.block"),
            ("tapón", "stat.block"),
            ("tapon", "stat.block"),
            ("tapo", "stat.block"),
            ("robo", "stat.steal"),
            ("rovo", "stat.steal"),
            ("perdida", "stat.turnover"),
            ("perdía", "stat.turnover"),
            ("pasos", "stat.turnover"),
            ("paso", "stat.turnover"),
            ("doble dribble", "stat.turnover"),
            ("doble drible", "stat.turnover"),
        ],
        substitutionKeywords: ["cambio", "sustitución", "reemplazo", "sustituye"],
        commandEvents: [
            ("inicio", "event.period"),
            ("primer cuarto", "event.period"),
            ("siguiente cuarto", "event.period"),
            ("cuarto concluido", "event.period"),
            ("pausa", "event.pause"),
            ("tiempo muerto", "event.pause"),
            ("continuar", "event.pause"),
            ("reanudar", "event.pause"),
            ("final", "event.game_end"),
            ("fin del partido", "event.game_end"),
            ("terminar", "event.game_end"),
            ("terminado", "event.game_end"),
        ],
        fuzzyMap: [],
        surnamePinyinOverrides: [:],
        pinyinVariantRules: [],
        multiPronunciations: [:],
        useLevenshteinMatching: true,
        levenshteinThreshold: (short: 1, long: 2),
        useAnchorMatching: false,
        anchorWords: [],
        stealTargetRule: .init(prefixesToStrip: ["a "])
    )
}