import Foundation

extension VoiceRulesData {

    static let korean = VoiceRulesData(
        locale: "ko-KR",
        speechRecognizerLocale: "ko-KR",
        shotKeywords: [
            ShotKeywordData(keyword: "자유투", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "프리스로우", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "프리스로", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "투", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "투포인트", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "두", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "2", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "쓰리", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "쓰리포인트", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "스리", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "스리포인트", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "3", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "레이업", eventPrefix: "stat.layup"),
            ShotKeywordData(keyword: "레이엄", eventPrefix: "stat.layup"),
            ShotKeywordData(keyword: "미드", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "미드레인지", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "미드레인치", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "페인트", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "페인츠", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "인사이드", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "보너스", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "보나스", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "앤드 원", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "엔드 원", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "원 플러스 원", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "팟백", eventPrefix: "stat.putback"),
            ShotKeywordData(keyword: "putback", eventPrefix: "stat.putback"),
            ShotKeywordData(keyword: "팥백", eventPrefix: "stat.putback"),
            ShotKeywordData(keyword: "덩크", eventPrefix: "stat.dunk"),
            ShotKeywordData(keyword: "덩크슛", eventPrefix: "stat.dunk"),
            ShotKeywordData(keyword: "dunk", eventPrefix: "stat.dunk"),
            ShotKeywordData(keyword: "슛", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "속공", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "드라이브", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "점프슛", eventPrefix: "stat.two")
        ],
        madeStates: ["성공", "들어갔다", "득점", "성공했다"],
        missedStates: ["실패", "빗나감", "블록", "못 넣음", "안 들어감", "놓침", "노", "에어볼"],
        statEvents: [
            ["파울", "stat.foul"],
            ["파올", "stat.foul"],
            ["리바운드", "stat.rebound"],
            ["리파운드", "stat.rebound"],
            ["리바운", "stat.rebound"],
            ["공격 리바운드", "stat.offensiveRebound"],
            ["공격 리파운드", "stat.offensiveRebound"],
            ["공격 리바운", "stat.offensiveRebound"],
            ["수비 리바운드", "stat.defensiveRebound"],
            ["수비 리파운드", "stat.defensiveRebound"],
            ["수비 리바운", "stat.defensiveRebound"],
            ["어시스트", "stat.assist"],
            ["어시스", "stat.assist"],
            ["블록", "stat.block"],
            ["프록", "stat.block"],
            ["블럭", "stat.block"],
            ["스틸", "stat.steal"],
            ["스티일", "stat.steal"],
            ["턴오버", "stat.turnover"],
            ["턴노버", "stat.turnover"],
            ["턴오바", "stat.turnover"],
            ["트래블링", "stat.turnover"],
            ["트래블린", "stat.turnover"],
            ["더블드리블", "stat.turnover"],
            ["더블드리블링", "stat.turnover"]
        ],
        substitutionKeywords: ["교체", "체인지", "교체 투입"],
        commandEvents: [
            ["시작", "event.period"],
            ["첫 쿼터", "event.period"],
            ["다음 쿼터", "event.period"],
            ["쿼터종결", "event.period"],
            ["일시정지", "event.pause"],
            ["타임아웃", "event.pause"],
            ["스톱", "event.pause"],
            ["재개", "event.pause"],
            ["계속", "event.pause"],
            ["종료", "event.game_end"],
            ["경기종료", "event.game_end"],
            ["끝", "event.game_end"],
            ["파이널", "event.game_end"],
            ["실행 취소", "event.undo"],
            ["되돌리기", "event.undo"],
            ["재실행", "event.redo"],
            ["다시 실행", "event.redo"]
        ],
        fuzzyMap: nil,
        surnamePinyinOverrides: nil,
        pinyinVariantRules: nil,
        multiPronunciations: nil,
        useLevenshteinMatching: true,
        levenshteinThresholdShort: 1,
        levenshteinThresholdLong: 2,
        useAnchorMatching: false,
        anchorWords: [],
        stealTargetRule: StealTargetRuleData(
                    extractFrom: "leftTextAfterPlayer",
                    suffixesToStrip: ["를", "을"],
                    segmentParticles: ["가", "를", "을"]
                )
    )
}