import Foundation

extension VoiceRulesData {

    static let italian = VoiceRulesData(
        locale: "it-IT",
        speechRecognizerLocale: "it-IT",
        shotKeywords: [
            ShotKeywordData(keyword: "due", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "due punti", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "du", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "2", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "tre", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "tre punti", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "trè", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "3", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "tripla", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "tripla punti", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "layup", eventPrefix: "stat.layup"),
            ShotKeywordData(keyword: "lay up", eventPrefix: "stat.layup"),
            ShotKeywordData(keyword: "media", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "media distanza", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "mezza distanza", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "dentro", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "pitturato", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "piturato", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "tiro libero", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "tiro libro", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "libero", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "libbero", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "libro", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "bonus", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "e uno", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "e un", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "putback", eventPrefix: "stat.putback"),
            ShotKeywordData(keyword: "put back", eventPrefix: "stat.putback"),
            ShotKeywordData(keyword: "schiacciata", eventPrefix: "stat.dunk"),
            ShotKeywordData(keyword: "dunk", eventPrefix: "stat.dunk"),
            ShotKeywordData(keyword: "slam dunk", eventPrefix: "stat.dunk"),
            ShotKeywordData(keyword: "tiro", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "contropiede", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "penetrazione", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "tiro in sospensione", eventPrefix: "stat.two")
        ],
        madeStates: ["segnato", "fatto", "dentro", "buono", "riuscito"],
        missedStates: ["sbagliato", "fuori", "bloccato", "mancato", "no", "aria"],
        statEvents: [
            ["fallo", "stat.foul"],
            ["falo", "stat.foul"],
            ["fallato", "stat.foul"],
            ["rimbalzo", "stat.rebound"],
            ["rimbalso", "stat.rebound"],
            ["rimbalza", "stat.rebound"],
            ["rimbalzo offensivo", "stat.offensiveRebound"],
            ["rimbalzo difensivo", "stat.defensiveRebound"],
            ["rimbalso offensivo", "stat.offensiveRebound"],
            ["rimbalso difensivo", "stat.defensiveRebound"],
            ["offensivo", "stat.offensiveRebound"],
            ["difensivo", "stat.defensiveRebound"],
            ["assist", "stat.assist"],
            ["asist", "stat.assist"],
            ["assiste", "stat.assist"],
            ["stoppata", "stat.block"],
            ["stòppata", "stat.block"],
            ["stopata", "stat.block"],
            ["stòpata", "stat.block"],
            ["palla rubata", "stat.steal"],
            ["palla rubato", "stat.steal"],
            ["rubata", "stat.steal"],
            ["perse", "stat.turnover"],
            ["perso", "stat.turnover"],
            ["passi", "stat.turnover"],
            ["paso", "stat.turnover"],
            ["doppio dribbling", "stat.turnover"],
            ["dopio dribbling", "stat.turnover"],
            ["passi", "stat.turnover"],
            ["violazione", "stat.turnover"]
        ],
        substitutionKeywords: ["cambio", "sostituzione", "sostituisci", "entra"],
        commandEvents: [
            ["inizio", "event.period"],
            ["primo quarto", "event.period"],
            ["prossimo quarto", "event.period"],
            ["quarto concluso", "event.period"],
            ["pausa", "event.pause"],
            ["timeout", "event.pause"],
            ["stop", "event.pause"],
            ["continuare", "event.pause"],
            ["riprendere", "event.pause"],
            ["fine", "event.game_end"],
            ["fine partita", "event.game_end"],
            ["finito", "event.game_end"],
            ["terminato", "event.game_end"],
            ["undo", "event.undo"],
            ["annulla", "event.undo"],
            ["redo", "event.redo"],
            ["ripeti", "event.redo"]
        ],
        fuzzyMap: nil,
        surnamePinyinOverrides: nil,
        pinyinVariantRules: nil,
        multiPronunciations: nil,
        useLevenshteinMatching: true,
        levenshteinThresholdShort: 1,
        levenshteinThresholdLong: 2,
        useAnchorMatching: false,
        anchorWords: [],
        stealTargetRule: StealTargetRuleData(
                    prefixesToStrip: ["a "]
                )
    )
}