import Foundation

extension VoiceRules {
    static let french = VoiceRules(
        locale: Locale(identifier: "fr-FR"),
        speechRecognizerLocale: Locale(identifier: "fr-FR"),
        shotKeywords: [
            .init(keyword: "deux", eventPrefix: "stat.two"),
            .init(keyword: "deux points", eventPrefix: "stat.two"),
            .init(keyword: "deu", eventPrefix: "stat.two"),
            .init(keyword: "de", eventPrefix: "stat.two"),
            .init(keyword: "2", eventPrefix: "stat.two"),
            .init(keyword: "trois", eventPrefix: "stat.three"),
            .init(keyword: "trois points", eventPrefix: "stat.three"),
            .init(keyword: "troi", eventPrefix: "stat.three"),
            .init(keyword: "troiz", eventPrefix: "stat.three"),
            .init(keyword: "troa", eventPrefix: "stat.three"),
            .init(keyword: "3", eventPrefix: "stat.three"),
            .init(keyword: "lay-up", eventPrefix: "stat.layup"),
            .init(keyword: "layup", eventPrefix: "stat.layup"),
            .init(keyword: "lay up", eventPrefix: "stat.layup"),
            .init(keyword: "couche", eventPrefix: "stat.layup"),
            .init(keyword: "couché", eventPrefix: "stat.layup"),
            .init(keyword: "mi-distance", eventPrefix: "stat.midRange"),
            .init(keyword: "mi distance", eventPrefix: "stat.midRange"),
            .init(keyword: "moyenne distance", eventPrefix: "stat.midRange"),
            .init(keyword: "intérieur", eventPrefix: "stat.paint"),
            .init(keyword: "interieur", eventPrefix: "stat.paint"),
            .init(keyword: "lancer franc", eventPrefix: "stat.freeThrow"),
            .init(keyword: "lancer fran", eventPrefix: "stat.freeThrow"),
            .init(keyword: "lance franc", eventPrefix: "stat.freeThrow"),
            .init(keyword: "lancer", eventPrefix: "stat.freeThrow"),
            .init(keyword: "lance", eventPrefix: "stat.freeThrow"),
            .init(keyword: "panier", eventPrefix: "stat.two"),
            .init(keyword: "panié", eventPrefix: "stat.two"),
            .init(keyword: "bonus", eventPrefix: "stat.bonus"),
            .init(keyword: "et un", eventPrefix: "stat.bonus"),
            .init(keyword: "et 1", eventPrefix: "stat.bonus"),
        ],
        madeStates: ["réussi", "bon", "dedans", "marqué", "rentré"],
        missedStates: ["raté", "dehors", "loupé", "contré", "manqué", "bloqué", "non", "airball"],
        statEvents: [
            ("faute", "stat.foul"),
            ("fot", "stat.foul"),
            ("fote", "stat.foul"),
            ("faut", "stat.foul"),
            ("rebond", "stat.rebound"),
            ("rebon", "stat.rebound"),
            ("rebond offensif", "stat.rebound"),
            ("rebond défensif", "stat.rebound"),
            ("rebond defensif", "stat.rebound"),
            ("passe", "stat.assist"),
            ("pas", "stat.assist"),
            ("passe décisive", "stat.assist"),
            ("passe decisive", "stat.assist"),
            ("contre", "stat.block"),
            ("contr", "stat.block"),
            ("contre-attaque", "stat.block"),
            ("interception", "stat.steal"),
            ("intersetion", "stat.steal"),
            ("perte de balle", "stat.turnover"),
            ("perte de bal", "stat.turnover"),
            ("marcher", "stat.turnover"),
            ("marche", "stat.turnover"),
            ("marché", "stat.turnover"),
            ("double dribble", "stat.turnover"),
            ("double drible", "stat.turnover"),
        ],
        substitutionKeywords: ["remplacement", "changement", "substitution", "remplace"],
        commandEvents: [
            ("début", "event.period"),
            ("entre-deux", "event.period"),
            ("mise en jeu", "event.period"),
            ("premier quart", "event.period"),
            ("premier quart-temps", "event.period"),
            ("quart suivant", "event.period"),
            ("pause", "event.pause"),
            ("arrêter", "event.pause"),
            ("temps mort", "event.pause"),
            ("continuer", "event.pause"),
            ("reprise", "event.pause"),
            ("reprendre", "event.pause"),
            ("fin", "event.game_end"),
            ("fin du match", "event.game_end"),
            ("terminé", "event.game_end"),
            ("fini", "event.game_end"),
        ],
        fuzzyMap: [],
        surnamePinyinOverrides: [:],
        pinyinVariantRules: [],
        useLevenshteinMatching: true,
        levenshteinThreshold: (short: 1, long: 2),
        useAnchorMatching: false,
        anchorWords: []
    )
}
