import Foundation

extension VoiceRules {
    static let korean = VoiceRules(
        locale: Locale(identifier: "ko-KR"),
        speechRecognizerLocale: Locale(identifier: "ko-KR"),
        shotKeywords: [
            .init(keyword: "자유투", eventPrefix: "stat.freeThrow"),
            .init(keyword: "프리스로우", eventPrefix: "stat.freeThrow"),
            .init(keyword: "투", eventPrefix: "stat.two"),
            .init(keyword: "투포인트", eventPrefix: "stat.two"),
            .init(keyword: "두", eventPrefix: "stat.two"),
            .init(keyword: "2", eventPrefix: "stat.two"),
            .init(keyword: "쓰리", eventPrefix: "stat.three"),
            .init(keyword: "쓰리포인트", eventPrefix: "stat.three"),
            .init(keyword: "스리", eventPrefix: "stat.three"),
            .init(keyword: "3", eventPrefix: "stat.three"),
            .init(keyword: "레이업", eventPrefix: "stat.layup"),
            .init(keyword: "미드", eventPrefix: "stat.midRange"),
            .init(keyword: "미드레인지", eventPrefix: "stat.midRange"),
            .init(keyword: "페인트", eventPrefix: "stat.paint"),
            .init(keyword: "인사이드", eventPrefix: "stat.paint"),
            .init(keyword: "보너스", eventPrefix: "stat.bonus"),
            .init(keyword: "앤드 원", eventPrefix: "stat.bonus"),
            .init(keyword: "원 플러스 원", eventPrefix: "stat.bonus"),
        ],
        madeStates: [],
        missedStates: ["실패", "빗나감", "블록", "못 넣음"],
        statEvents: [
            ("파울", "stat.foul"),
            ("리바운드", "stat.rebound"),
            ("리파운드", "stat.rebound"),
            ("공격 리바운드", "stat.rebound"),
            ("수비 리바운드", "stat.rebound"),
            ("어시스트", "stat.assist"),
            ("블록", "stat.block"),
            ("프록", "stat.block"),
            ("스틸", "stat.steal"),
            ("턴오버", "stat.turnover"),
            ("턴노버", "stat.turnover"),
            ("트래블링", "stat.turnover"),
            ("더블드리블", "stat.turnover"),
        ],
        substitutionKeywords: ["교체", "체인지", "교체 투입"],
        commandEvents: [
            ("시작", "event.period"),
            ("첫 쿼터", "event.period"),
            ("다음 쿼터", "event.period"),
            ("일시정지", "event.pause"),
            ("타임아웃", "event.pause"),
            ("재개", "event.pause"),
            ("계속", "event.pause"),
            ("종료", "event.game_end"),
            ("경기종료", "event.game_end"),
        ],
        fuzzyMap: [],
        surnamePinyinOverrides: [:]
    )
}
