import Foundation

extension VoiceRulesData {

    static let spanish = VoiceRulesData(
        locale: "es-ES",
        speechRecognizerLocale: "es-ES",
        shotKeywords: [
            ShotKeywordData(keyword: "dos", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "dos puntos", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "do", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "doz", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "2", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "tres", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "tres puntos", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "tre", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "treh", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "trez", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "3", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "bandeja", eventPrefix: "stat.layup"),
            ShotKeywordData(keyword: "bandecha", eventPrefix: "stat.layup"),
            ShotKeywordData(keyword: "media", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "media distancia", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "media distansia", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "pintura", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "interior", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "postear", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "tiro libre", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "tiro libra", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "libre", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "libra", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "bonus", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "y uno", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "i uno", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "putback", eventPrefix: "stat.putback"),
            ShotKeywordData(keyword: "put back", eventPrefix: "stat.putback"),
            ShotKeywordData(keyword: "mate", eventPrefix: "stat.dunk"),
            ShotKeywordData(keyword: "clavada", eventPrefix: "stat.dunk"),
            ShotKeywordData(keyword: "dunk", eventPrefix: "stat.dunk")
        ],
        madeStates: ["anotó", "entró", "metió", "canasta", "bueno"],
        missedStates: ["fallado", "fuera", "bloqueado", "perdido", "no", "fallo", "aire"],
        statEvents: [
            ["falta", "stat.foul"],
            ["farta", "stat.foul"],
            ["faldo", "stat.foul"],
            ["rebote", "stat.rebound"],
            ["revote", "stat.rebound"],
            ["rebota", "stat.rebound"],
            ["rebote ofensivo", "stat.offensiveRebound"],
            ["revote ofensivo", "stat.offensiveRebound"],
            ["rebota ofensivo", "stat.offensiveRebound"],
            ["rebote defensivo", "stat.defensiveRebound"],
            ["revote defensivo", "stat.defensiveRebound"],
            ["rebota defensivo", "stat.defensiveRebound"],
            ["asistencia", "stat.assist"],
            ["asistensa", "stat.assist"],
            ["asiste", "stat.assist"],
            ["bloqueo", "stat.block"],
            ["bloquel", "stat.block"],
            ["tapón", "stat.block"],
            ["tapon", "stat.block"],
            ["tapo", "stat.block"],
            ["robo", "stat.steal"],
            ["rovo", "stat.steal"],
            ["perdida", "stat.turnover"],
            ["perdía", "stat.turnover"],
            ["pasos", "stat.turnover"],
            ["paso", "stat.turnover"],
            ["doble dribble", "stat.turnover"],
            ["doble drible", "stat.turnover"],
            ["pasos", "stat.turnover"],
            ["violación", "stat.turnover"]
        ],
        substitutionKeywords: ["cambio", "sustitución", "reemplazo", "sustituye"],
        commandEvents: [
            ["inicio", "event.period"],
            ["primer cuarto", "event.period"],
            ["siguiente cuarto", "event.period"],
            ["cuarto concluido", "event.period"],
            ["pausa", "event.pause"],
            ["tiempo muerto", "event.pause"],
            ["stop", "event.pause"],
            ["continuar", "event.pause"],
            ["reanudar", "event.pause"],
            ["final", "event.game_end"],
            ["fin del partido", "event.game_end"],
            ["terminar", "event.game_end"],
            ["terminado", "event.game_end"],
            ["undo", "event.undo"],
            ["deshacer", "event.undo"],
            ["redo", "event.redo"],
            ["rehacer", "event.redo"]
        ],
        fuzzyMap: nil,
        surnamePinyinOverrides: nil,
        pinyinVariantRules: nil,
        multiPronunciations: nil,
        useLevenshteinMatching: true,
        levenshteinThresholdShort: 1,
        levenshteinThresholdLong: 2,
        useAnchorMatching: false,
        anchorWords: [],
        stealTargetRule: StealTargetRuleData(
                    prefixesToStrip: ["a "]
                )
    )
}