import Foundation

extension VoiceRules {
    static let japanese = VoiceRules(
        locale: Locale(identifier: "ja-JP"),
        speechRecognizerLocale: Locale(identifier: "ja-JP"),
        shotKeywords: [
            .init(keyword: "ツー", eventPrefix: "stat.two"),
            .init(keyword: "ツーポイント", eventPrefix: "stat.two"),
            .init(keyword: "ツ", eventPrefix: "stat.two"),
            .init(keyword: "2", eventPrefix: "stat.two"),
            .init(keyword: "スリー", eventPrefix: "stat.three"),
            .init(keyword: "スリーポイント", eventPrefix: "stat.three"),
            .init(keyword: "スリ", eventPrefix: "stat.three"),
            .init(keyword: "3", eventPrefix: "stat.three"),
            .init(keyword: "レイアップ", eventPrefix: "stat.layup"),
            .init(keyword: "レアップ", eventPrefix: "stat.layup"),
            .init(keyword: "ミドル", eventPrefix: "stat.midRange"),
            .init(keyword: "ミドルレンジ", eventPrefix: "stat.midRange"),
            .init(keyword: "ペイント", eventPrefix: "stat.paint"),
            .init(keyword: "インサイド", eventPrefix: "stat.paint"),
            .init(keyword: "ポストアップ", eventPrefix: "stat.paint"),
            .init(keyword: "フリースロー", eventPrefix: "stat.freeThrow"),
            .init(keyword: "フリスロー", eventPrefix: "stat.freeThrow"),
            .init(keyword: "フリスロ", eventPrefix: "stat.freeThrow"),
            .init(keyword: "フリー", eventPrefix: "stat.freeThrow"),
            .init(keyword: "ボーナス", eventPrefix: "stat.bonus"),
            .init(keyword: "アンドワン", eventPrefix: "stat.bonus"),
            .init(keyword: "ワンプラスワン", eventPrefix: "stat.bonus"),
        ],
        madeStates: [],
        missedStates: ["外した", "入らない", "ミス", "失敗", "ブロック"],
        statEvents: [
            ("ファウル", "stat.foul"),
            ("ファール", "stat.foul"),
            ("リバウンド", "stat.rebound"),
            ("リバウン", "stat.rebound"),
            ("オフェンスリバウンド", "stat.rebound"),
            ("ディフェンスリバウンド", "stat.rebound"),
            ("アシスト", "stat.assist"),
            ("アシト", "stat.assist"),
            ("ブロック", "stat.block"),
            ("ブロク", "stat.block"),
            ("スティール", "stat.steal"),
            ("スティル", "stat.steal"),
            ("ターンオーバー", "stat.turnover"),
            ("ターンオーバ", "stat.turnover"),
            ("タンオーバ", "stat.turnover"),
            ("トラベリング", "stat.turnover"),
            ("バイオレーション", "stat.turnover"),
            ("ダブルドリブル", "stat.turnover"),
        ],
        substitutionKeywords: ["交代", "選手交代", "チェンジ", "入れ替え"],
        commandEvents: [
            ("開始", "event.period"),
            ("スタート", "event.period"),
            ("第1クオーター", "event.period"),
            ("次のクオーター", "event.period"),
            ("次", "event.period"),
            ("一時停止", "event.pause"),
            ("タイムアウト", "event.pause"),
            ("休憩", "event.pause"),
            ("再開", "event.pause"),
            ("リスタート", "event.pause"),
            ("続ける", "event.pause"),
            ("終了", "event.game_end"),
            ("試合終了", "event.game_end"),
        ],
        fuzzyMap: [],
        surnamePinyinOverrides: [:]
    )
}
