import Foundation

extension VoiceRules {
    static let traditionalChinese = VoiceRules(
        locale: Locale(identifier: "zh-Hant-TW"),
        speechRecognizerLocale: Locale(identifier: "zh-TW"),
        shotKeywords: [
            .init(keyword: "兩分", eventPrefix: "stat.two"),
            .init(keyword: "2分", eventPrefix: "stat.two"),
            .init(keyword: "三分", eventPrefix: "stat.three"),
            .init(keyword: "3分", eventPrefix: "stat.three"),
            .init(keyword: "上籃", eventPrefix: "stat.layup"),
            .init(keyword: "中投", eventPrefix: "stat.midRange"),
            .init(keyword: "中距離", eventPrefix: "stat.midRange"),
            .init(keyword: "籃下", eventPrefix: "stat.paint"),
            .init(keyword: "內線", eventPrefix: "stat.paint"),
            .init(keyword: "罰球", eventPrefix: "stat.freeThrow"),
            .init(keyword: "罰籃", eventPrefix: "stat.freeThrow"),
            .init(keyword: "發球", eventPrefix: "stat.freeThrow"),
            .init(keyword: "加罰", eventPrefix: "stat.bonus"),
            .init(keyword: "山分", eventPrefix: "stat.three"),
            .init(keyword: "散分", eventPrefix: "stat.three"),
            .init(keyword: "三份", eventPrefix: "stat.three"),
            .init(keyword: "法球", eventPrefix: "stat.freeThrow"),
            .init(keyword: "上南", eventPrefix: "stat.layup"),
            .init(keyword: "桑蘭", eventPrefix: "stat.layup"),
            .init(keyword: "總投", eventPrefix: "stat.midRange"),
            .init(keyword: "南夏", eventPrefix: "stat.paint"),
            .init(keyword: "加法", eventPrefix: "stat.bonus"),
        ],
        madeStates: ["命中", "進", "得分", "成功"],
        missedStates: ["未中", "沒中", "不中", "不進", "沒進", "打鐵"],
        statEvents: [
            ("犯規", "stat.foul"),
            ("籃板", "stat.rebound"),
            ("板", "stat.rebound"),
            ("nanban", "stat.rebound"),
            ("nan ban", "stat.rebound"),
            ("前場板", "stat.offensiveRebound"),
            ("qian chang ban", "stat.offensiveRebound"),
            ("qianchangban", "stat.offensiveRebound"),
            ("後場板", "stat.defensiveRebound"),
            ("hou chang ban", "stat.defensiveRebound"),
            ("houchangban", "stat.defensiveRebound"),
            ("搶板", "stat.rebound"),
            ("助攻", "stat.assist"),
            ("蓋帽", "stat.block"),
            ("封蓋", "stat.block"),
            ("抄截", "stat.steal"),
            ("失誤", "stat.turnover"),
            ("方歸", "stat.foul"),
            ("lan ban", "stat.rebound"),
            ("走步", "stat.turnover"),
            ("違例", "stat.turnover"),
        ],
        substitutionKeywords: ["換人", "替換", "換上", "換下", "換"],
        commandEvents: [
            ("開始", "event.period"),
            ("第一節", "event.period"),
            ("第1節", "event.period"),
            ("第二節", "event.period"),
            ("第2節", "event.period"),
            ("第三節", "event.period"),
            ("第3節", "event.period"),
            ("第四節", "event.period"),
            ("第4節", "event.period"),
            ("下一節", "event.period"),
            ("結束本節", "event.period"),
            ("節結束", "event.period"),
            ("暫停", "event.pause"),
            ("停表", "event.pause"),
            ("繼續", "event.pause"),
            ("繼續比賽", "event.pause"),
            ("比賽繼續", "event.pause"),
        ],
        fuzzyMap: [
            ("zh", "z"), ("ch", "c"), ("sh", "s"),
            ("r", "l"),
            ("eng", "en"), ("ing", "in"), ("ang", "an"),
        ],
        surnamePinyinOverrides: [
            "曾": ["zeng"],
            "單": ["shan"],
            "朴": ["piao"],
            "解": ["xie"],
            "區": ["ou"],
            "仇": ["qiu"],
            "蓋": ["ge"],
            "查": ["zha"],
            "華": ["hua"],
            "繆": ["miao"],
            "覃": ["qin"],
            "芮": ["rui"],
            "逄": ["pang"],
        ],
        pinyinVariantRules: [
            ("zh", "z"), ("z", "zh"),
            ("ch", "c"), ("c", "ch"),
            ("sh", "s"), ("s", "sh"),
            ("r", "l"), ("l", "r"),
            ("n", "l"), ("l", "n"),
            ("m", "n"), ("n", "m"),
            ("eng", "en"), ("en", "eng"),
            ("ing", "in"), ("in", "ing"),
            ("ang", "an"), ("an", "ang"),
            ("ian", "uan"), ("uan", "ian"),
        ],
        multiPronunciations: [
            "長": ["chang", "zhang"],
            "行": ["xing", "hang"],
            "樂": ["le", "yue"],
            "傳": ["chuan", "zhuan"],
            "重": ["zhong", "chong"],
            "的": ["de", "di"],
            "地": ["de", "di"],
        ],
        useLevenshteinMatching: false,
        levenshteinThreshold: (short: 1, long: 2),
        useAnchorMatching: false,
        anchorWords: []
    )
}
