import Foundation

extension VoiceRulesData {

    static let german = VoiceRulesData(
        locale: "de-DE",
        speechRecognizerLocale: "de-DE",
        shotKeywords: [
            ShotKeywordData(keyword: "zwei", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "zwei punkte", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "zvei", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "2", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "drei", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "drei punkte", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "dreier", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "dreyer", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "3", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "layup", eventPrefix: "stat.layup"),
            ShotKeywordData(keyword: "lay up", eventPrefix: "stat.layup"),
            ShotKeywordData(keyword: "mitteldistanz", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "mittlere distanz", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "mittel distanz", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "korb", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "korb nähe", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "korbnähe", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "freiwurf", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "frei wurf", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "freivurf", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "bonus", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "and one", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "and won", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "putback", eventPrefix: "stat.putback"),
            ShotKeywordData(keyword: "put back", eventPrefix: "stat.putback"),
            ShotKeywordData(keyword: "dunk", eventPrefix: "stat.dunk"),
            ShotKeywordData(keyword: "dunking", eventPrefix: "stat.dunk"),
            ShotKeywordData(keyword: "slam dunk", eventPrefix: "stat.dunk")
        ],
        madeStates: ["getroffen", "drin", "gut", "rein", "erfolg"],
        missedStates: ["verfehlt", "daneben", "blockiert", "nicht", "vorbei", "nein", "miss"],
        statEvents: [
            ["foul", "stat.foul"],
            ["faul", "stat.foul"],
            ["fowl", "stat.foul"],
            ["rebound", "stat.rebound"],
            ["ribaund", "stat.rebound"],
            ["abpraller", "stat.rebound"],
            ["abpraler", "stat.rebound"],
            ["offensiv rebound", "stat.offensiveRebound"],
            ["offensiv ribaund", "stat.offensiveRebound"],
            ["offensiv abpraller", "stat.offensiveRebound"],
            ["offensiv abpraler", "stat.offensiveRebound"],
            ["defensiv rebound", "stat.defensiveRebound"],
            ["defensiv ribaund", "stat.defensiveRebound"],
            ["defensiv abpraller", "stat.defensiveRebound"],
            ["defensiv abpraler", "stat.defensiveRebound"],
            ["assist", "stat.assist"],
            ["asist", "stat.assist"],
            ["vorlage", "stat.assist"],
            ["forlage", "stat.assist"],
            ["block", "stat.block"],
            ["blok", "stat.block"],
            ["bloc", "stat.block"],
            ["steal", "stat.steal"],
            ["stil", "stat.steal"],
            ["diebstahl", "stat.steal"],
            ["diepstahl", "stat.steal"],
            ["turnover", "stat.turnover"],
            ["ballverlust", "stat.turnover"],
            ["ball verlust", "stat.turnover"],
            ["schrittfehler", "stat.turnover"],
            ["schritt fehler", "stat.turnover"]
        ],
        substitutionKeywords: ["wechsel", "auswechslung", "ersetzen", "rein", "raus"],
        commandEvents: [
            ["start", "event.period"],
            ["sprungball", "event.period"],
            ["tip off", "event.period"],
            ["erstes viertel", "event.period"],
            ["nächstes viertel", "event.period"],
            ["viertel um", "event.period"],
            ["pause", "event.pause"],
            ["auszeit", "event.pause"],
            ["weiter", "event.pause"],
            ["weiterspielen", "event.pause"],
            ["ende", "event.game_end"],
            ["spielende", "event.game_end"],
            ["schluss", "event.game_end"],
            ["fertig", "event.game_end"],
            ["undo", "event.undo"],
            ["redo", "event.redo"]
        ],
        fuzzyMap: nil,
        surnamePinyinOverrides: nil,
        pinyinVariantRules: nil,
        multiPronunciations: nil,
        useLevenshteinMatching: true,
        levenshteinThresholdShort: 1,
        levenshteinThresholdLong: 2,
        useAnchorMatching: false,
        anchorWords: [],
        stealTargetRule: nil
    )
}