import Foundation

extension VoiceRulesData {

    static let french = VoiceRulesData(
        locale: "fr-FR",
        speechRecognizerLocale: "fr-FR",
        shotKeywords: [
            ShotKeywordData(keyword: "deux", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "deux points", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "deu", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "de", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "2", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "trois", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "trois points", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "troi", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "troiz", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "troa", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "3", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "lay-up", eventPrefix: "stat.layup"),
            ShotKeywordData(keyword: "layup", eventPrefix: "stat.layup"),
            ShotKeywordData(keyword: "lay up", eventPrefix: "stat.layup"),
            ShotKeywordData(keyword: "couche", eventPrefix: "stat.layup"),
            ShotKeywordData(keyword: "couché", eventPrefix: "stat.layup"),
            ShotKeywordData(keyword: "mi-distance", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "mi distance", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "moyenne distance", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "intérieur", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "interieur", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "lancer franc", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "lancer fran", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "lance franc", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "lancer", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "lance", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "panier", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "panié", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "bonus", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "et un", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "et 1", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "putback", eventPrefix: "stat.putback"),
            ShotKeywordData(keyword: "put back", eventPrefix: "stat.putback"),
            ShotKeywordData(keyword: "dunk", eventPrefix: "stat.dunk"),
            ShotKeywordData(keyword: "slam dunk", eventPrefix: "stat.dunk"),
            ShotKeywordData(keyword: "dunker", eventPrefix: "stat.dunk")
        ],
        madeStates: ["réussi", "bon", "dedans", "marqué", "rentré"],
        missedStates: ["raté", "dehors", "loupé", "contré", "manqué", "bloqué", "non", "airball"],
        statEvents: [
            ["faute", "stat.foul"],
            ["fot", "stat.foul"],
            ["fote", "stat.foul"],
            ["faut", "stat.foul"],
            ["rebond", "stat.rebound"],
            ["rebon", "stat.rebound"],
            ["rebond offensif", "stat.offensiveRebound"],
            ["rebon offensif", "stat.offensiveRebound"],
            ["rebond défensif", "stat.defensiveRebound"],
            ["rebond defensif", "stat.defensiveRebound"],
            ["rebon défensif", "stat.defensiveRebound"],
            ["rebon defensif", "stat.defensiveRebound"],
            ["passe", "stat.assist"],
            ["pas", "stat.assist"],
            ["passe décisive", "stat.assist"],
            ["passe decisive", "stat.assist"],
            ["contre", "stat.block"],
            ["contr", "stat.block"],
            ["contre-attaque", "stat.block"],
            ["interception", "stat.steal"],
            ["intersetion", "stat.steal"],
            ["perte de balle", "stat.turnover"],
            ["perte de bal", "stat.turnover"],
            ["marcher", "stat.turnover"],
            ["marche", "stat.turnover"],
            ["marché", "stat.turnover"],
            ["double dribble", "stat.turnover"],
            ["double drible", "stat.turnover"]
        ],
        substitutionKeywords: ["remplacement", "changement", "substitution", "remplace"],
        commandEvents: [
            ["début", "event.period"],
            ["entre-deux", "event.period"],
            ["mise en jeu", "event.period"],
            ["premier quart", "event.period"],
            ["premier quart-temps", "event.period"],
            ["quart suivant", "event.period"],
            ["quart achevé", "event.period"],
            ["pause", "event.pause"],
            ["arrêter", "event.pause"],
            ["temps mort", "event.pause"],
            ["continuer", "event.pause"],
            ["reprise", "event.pause"],
            ["reprendre", "event.pause"],
            ["fin", "event.game_end"],
            ["fin du match", "event.game_end"],
            ["terminé", "event.game_end"],
            ["fini", "event.game_end"],
            ["undo", "event.undo"],
            ["redo", "event.redo"]
        ],
        fuzzyMap: nil,
        surnamePinyinOverrides: nil,
        pinyinVariantRules: nil,
        multiPronunciations: nil,
        useLevenshteinMatching: true,
        levenshteinThresholdShort: 1,
        levenshteinThresholdLong: 2,
        useAnchorMatching: false,
        anchorWords: [],
        stealTargetRule: nil
    )
}