import Foundation

extension VoiceRules {
    static let english = VoiceRules(
        locale: Locale(identifier: "en-US"),
        speechRecognizerLocale: Locale(identifier: "en-US"),
        shotKeywords: [
            .init(keyword: "two", eventPrefix: "stat.two"),
            .init(keyword: "two pointer", eventPrefix: "stat.two"),
            .init(keyword: "too", eventPrefix: "stat.two"),
            .init(keyword: "2", eventPrefix: "stat.two"),
            .init(keyword: "2 pointer", eventPrefix: "stat.two"),
            .init(keyword: "three free throw", eventPrefix: "stat.freeThrow"),
            .init(keyword: "three", eventPrefix: "stat.three"),
            .init(keyword: "three pointer", eventPrefix: "stat.three"),
            .init(keyword: "3", eventPrefix: "stat.three"),
            .init(keyword: "3 pointer", eventPrefix: "stat.three"),
            .init(keyword: "trey", eventPrefix: "stat.three"),
            .init(keyword: "tree", eventPrefix: "stat.three"),
            .init(keyword: "layup", eventPrefix: "stat.layup"),
            .init(keyword: "lay up", eventPrefix: "stat.layup"),
            .init(keyword: "mid", eventPrefix: "stat.midRange"),
            .init(keyword: "mid range", eventPrefix: "stat.midRange"),
            .init(keyword: "jumper", eventPrefix: "stat.midRange"),
            .init(keyword: "jump shot", eventPrefix: "stat.midRange"),
            .init(keyword: "pull up", eventPrefix: "stat.midRange"),
            .init(keyword: "paint", eventPrefix: "stat.paint"),
            .init(keyword: "inside", eventPrefix: "stat.paint"),
            .init(keyword: "post up", eventPrefix: "stat.paint"),
            .init(keyword: "free throw", eventPrefix: "stat.freeThrow"),
            .init(keyword: "foul shot", eventPrefix: "stat.freeThrow"),
            .init(keyword: "fowl shot", eventPrefix: "stat.freeThrow"),
            .init(keyword: "faul shot", eventPrefix: "stat.freeThrow"),
            .init(keyword: "four shot", eventPrefix: "stat.freeThrow"),
            .init(keyword: "free through", eventPrefix: "stat.freeThrow"),
            .init(keyword: "free thru", eventPrefix: "stat.freeThrow"),
            .init(keyword: "free", eventPrefix: "stat.freeThrow"),
            .init(keyword: "bonus", eventPrefix: "stat.bonus"),
            .init(keyword: "and one", eventPrefix: "stat.bonus"),
        ],
        madeStates: ["got", "get"],
        missedStates: ["missed", "no", "miss", "not", "know", "blocked", "out", "airball", "brick", "short"],
        statEvents: [
            ("foul", "stat.foul"),
            ("fowl", "stat.foul"),
            ("faul", "stat.foul"),
            ("four", "stat.foul"),
            ("reach", "stat.foul"),
            ("hack", "stat.foul"),
            ("rebound", "stat.rebound"),
            ("rebounds", "stat.rebound"),
            ("board", "stat.rebound"),
            ("boards", "stat.rebound"),
            ("glass", "stat.rebound"),
            ("rebaund", "stat.rebound"),
            ("ribaund", "stat.rebound"),
            ("rebo", "stat.rebound"),
            ("offensive rebound", "stat.rebound"),
            ("defensive rebound", "stat.rebound"),
            ("assist", "stat.assist"),
            ("a sister", "stat.assist"),
            ("dime", "stat.assist"),
            ("block", "stat.block"),
            ("bloc", "stat.block"),
            ("swat", "stat.block"),
            ("steal", "stat.steal"),
            ("steel", "stat.steal"),
            ("takeaway", "stat.steal"),
            ("turnover", "stat.turnover"),
            ("turn over", "stat.turnover"),
            ("travel", "stat.turnover"),
            ("walk", "stat.turnover"),
            ("violation", "stat.turnover"),
            ("carry", "stat.turnover"),
            ("double dribble", "stat.turnover"),
        ],
        substitutionKeywords: ["sub", "substitution", "substitute", "replace", "swap", "change", "switch", "in for"],
        commandEvents: [
            ("start", "event.period"),
            ("begin", "event.period"),
            ("tip off", "event.period"),
            ("jump ball", "event.period"),
            ("next quarter", "event.period"),
            ("pause", "event.pause"),
            ("timeout", "event.pause"),
            ("stop", "event.pause"),
            ("resume", "event.pause"),
            ("continue", "event.pause"),
            ("unpause", "event.pause"),
            ("play", "event.pause"),
            ("end", "event.game_end"),
            ("finish", "event.game_end"),
            ("game over", "event.game_end"),
            ("final", "event.game_end"),
        ],
        fuzzyMap: [],
        surnamePinyinOverrides: [:],
        pinyinVariantRules: [],
        useLevenshteinMatching: true,
        levenshteinThreshold: (short: 1, long: 2),
        useAnchorMatching: true,
        anchorWords: ["made", "got", "get", "missed", "miss", "no", "not", "know"]
    )
}
