import Foundation

extension VoiceRulesData {

    static let russian = VoiceRulesData(
        locale: "ru-RU",
        speechRecognizerLocale: "ru-RU",
        shotKeywords: [
            ShotKeywordData(keyword: "два", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "двушка", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "два очка", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "2 очка", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "дла", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "три", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "трёшка", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "трешка", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "3 очка", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "тли", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "3", eventPrefix: "stat.three"),
            ShotKeywordData(keyword: "лей-ап", eventPrefix: "stat.layup"),
            ShotKeywordData(keyword: "лей ап", eventPrefix: "stat.layup"),
            ShotKeywordData(keyword: "лэй-ап", eventPrefix: "stat.layup"),
            ShotKeywordData(keyword: "средний", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "средний бросок", eventPrefix: "stat.midRange"),
            ShotKeywordData(keyword: "краска", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "изнутри", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "из под кольца", eventPrefix: "stat.paint"),
            ShotKeywordData(keyword: "штрафной", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "штрафной бросок", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "штрафный", eventPrefix: "stat.freeThrow"),
            ShotKeywordData(keyword: "бонус", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "бонас", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "и один", eventPrefix: "stat.bonus"),
            ShotKeywordData(keyword: "putback", eventPrefix: "stat.putback"),
            ShotKeywordData(keyword: "put back", eventPrefix: "stat.putback"),
            ShotKeywordData(keyword: "данк", eventPrefix: "stat.dunk"),
            ShotKeywordData(keyword: "слэм-данк", eventPrefix: "stat.dunk"),
            ShotKeywordData(keyword: "дануть", eventPrefix: "stat.dunk"),
            ShotKeywordData(keyword: "бросок", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "быстрый прорыв", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "проход", eventPrefix: "stat.two"),
            ShotKeywordData(keyword: "прыжок", eventPrefix: "stat.two")
        ],
        madeStates: ["попал", "забил", "есть", "удачно", "зашёл"],
        missedStates: ["промах", "мимо", "заблокировали", "не попал", "нет", "мимо кольца"],
        statEvents: [
            ["фол", "stat.foul"],
            ["фал", "stat.foul"],
            ["фаул", "stat.foul"],
            ["вал", "stat.foul"],
            ["подбор", "stat.rebound"],
            ["потбор", "stat.rebound"],
            ["падбор", "stat.rebound"],
            ["подбор в нападении", "stat.offensiveRebound"],
            ["потбор в нападении", "stat.offensiveRebound"],
            ["падбор в нападении", "stat.offensiveRebound"],
            ["подбор в защите", "stat.defensiveRebound"],
            ["потбор в защите", "stat.defensiveRebound"],
            ["падбор в защите", "stat.defensiveRebound"],
            ["передача", "stat.assist"],
            ["ассист", "stat.assist"],
            ["асист", "stat.assist"],
            ["пас", "stat.assist"],
            ["блок", "stat.block"],
            ["блок-шот", "stat.block"],
            ["блок шот", "stat.block"],
            ["перехват", "stat.steal"],
            ["пирихват", "stat.steal"],
            ["потеря", "stat.turnover"],
            ["патеря", "stat.turnover"],
            ["пробежка", "stat.turnover"],
            ["прабежка", "stat.turnover"],
            ["нарушение", "stat.turnover"],
            ["нарушенье", "stat.turnover"],
            ["двойное ведение", "stat.turnover"],
            ["пронос", "stat.turnover"]
        ],
        substitutionKeywords: ["замена", "меняем", "заменить"],
        commandEvents: [
            ["начало", "event.period"],
            ["старт", "event.period"],
            ["первая четверть", "event.period"],
            ["следующая четверть", "event.period"],
            ["четверть завершена", "event.period"],
            ["пауза", "event.pause"],
            ["тайм-аут", "event.pause"],
            ["продолжить", "event.pause"],
            ["конец", "event.game_end"],
            ["конец игры", "event.game_end"],
            ["финал", "event.game_end"],
            ["закончили", "event.game_end"],
            ["undo", "event.undo"],
            ["отменить", "event.undo"],
            ["redo", "event.redo"],
            ["повторить", "event.redo"]
        ],
        fuzzyMap: nil,
        surnamePinyinOverrides: nil,
        pinyinVariantRules: nil,
        multiPronunciations: nil,
        useLevenshteinMatching: true,
        levenshteinThresholdShort: 1,
        levenshteinThresholdLong: 2,
        useAnchorMatching: false,
        anchorWords: [],
        stealTargetRule: StealTargetRuleData(
            prefixesToStrip: ["у "]
        )
    )
}